# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "D5djEd5Ra7v/8mOh8yZs6Iec6BRanDz0N1d5yB0W2xxCPzW8ZDYiPFVicUfPFlNfQRugc3bu+VzQnQXLdyd6iGFllVrLFwSsEUFQnofu3lPute/O7dAghmWxbfdXPdUGvxEixA+eX6ApdJLwRVyO1SQuyxusk8PX5pqbQufUNxwAzJiWveRAIjSpA4KuNblm15Kgcwlz4KFoj/Bo0RsI7ECax5+qdOJT3KiGaX+Y7fkVkB2l2AsWXZhNxUC4oUx7UkainQv2msKV33BUXprgNiCFkgPu4FTEl2nijSvv9l2BmnBw0BCxnJ0kqF6pzqfT/Mco+lnWvygj4ds6ql1bf6ce5oA19acNAcYBNUVQ4j0oAqhhy+WsSmM5fnJAPeXHcnN8X88LuELfHcXrgguMNNQ4cHOopUaARSkLQkzY8M2pTbPWT34swb5OJ2JxCXFfTB+EfwTaJvK4OWuscqgs6uBoJeUX4G3tRj0aKfK4OmwO9mac6MNz55LFAQbPyDJjocEUz4TdSr9+XCC8dYzgDHxyllr9Fq2jEIm1TKr3Y8DaehoZDd+tA2qyMQl/ldQblYqZRY5G79d/sVn1hIO/KTxV4IeJ92wqkc9chTCY07tAEKCwHxD0+o9rIObBxg1p+M2+253zU5U2k3WOcR1EKGRjWgQR8+XEbVF5/DXWZ9E="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
