travis:
  secure:
    BINSTAR_TOKEN: D5djEd5Ra7v/8mOh8yZs6Iec6BRanDz0N1d5yB0W2xxCPzW8ZDYiPFVicUfPFlNfQRugc3bu+VzQnQXLdyd6iGFllVrLFwSsEUFQnofu3lPute/O7dAghmWxbfdXPdUGvxEixA+eX6ApdJLwRVyO1SQuyxusk8PX5pqbQufUNxwAzJiWveRAIjSpA4KuNblm15Kgcwlz4KFoj/Bo0RsI7ECax5+qdOJT3KiGaX+Y7fkVkB2l2AsWXZhNxUC4oUx7UkainQv2msKV33BUXprgNiCFkgPu4FTEl2nijSvv9l2BmnBw0BCxnJ0kqF6pzqfT/Mco+lnWvygj4ds6ql1bf6ce5oA19acNAcYBNUVQ4j0oAqhhy+WsSmM5fnJAPeXHcnN8X88LuELfHcXrgguMNNQ4cHOopUaARSkLQkzY8M2pTbPWT34swb5OJ2JxCXFfTB+EfwTaJvK4OWuscqgs6uBoJeUX4G3tRj0aKfK4OmwO9mac6MNz55LFAQbPyDJjocEUz4TdSr9+XCC8dYzgDHxyllr9Fq2jEIm1TKr3Y8DaehoZDd+tA2qyMQl/ldQblYqZRY5G79d/sVn1hIO/KTxV4IeJ92wqkc9chTCY07tAEKCwHxD0+o9rIObBxg1p+M2+253zU5U2k3WOcR1EKGRjWgQR8+XEbVF5/DXWZ9E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
